version: "3.9"

services:
  web:
    container_name: portfolio-simple-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: >
      sh -c "
        npm run build &&
        npm run start
      "

volumes:
  postgres-data:

networks:
  app-net:
    driver: bridge
