name: CI & CD (Next.js + Docker + GHCR)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  checks:
    name: Lint, typecheck & build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Build
        run: npm run build

  docker:
    name: Build & push Docker image to GHCR
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy over SSH (create compose + up)
    if: github.ref == 'refs/heads/main'
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || '22' }}
          script: |
            set -e
            REPO="${{ github.repository }}"
            IMAGE="ghcr.io/${REPO,,}:latest"

            mkdir -p ~/apps/portfolio-simple
            cat > ~/apps/portfolio-simple/docker-compose.prod.yml <<'YML'
            version: "3.9"
            services:
              web:
                image: __IMAGE__
                container_name: portfolio-simple-web
                restart: unless-stopped
                ports:
                  - "3000:3000"
                environment:
                  - NODE_ENV=production
                  - NEXT_TELEMETRY_DISABLED=1
            YML

            sed -i "s|__IMAGE__|$IMAGE|g" ~/apps/portfolio-simple/docker-compose.prod.yml

            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose -f ~/apps/portfolio-simple/docker-compose.prod.yml pull
            docker compose -f ~/apps/portfolio-simple/docker-compose.prod.yml up -d
            docker image prune -f
